from __future__ import annotations

import csv
import json
import tempfile
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from dmx_crawler.config import Settings, load_categories, load_locations
from dmx_crawler.db import Database
from dmx_crawler.models import DeliveryInfo, LocationSnapshot, ProductLink
from dmx_crawler.parsers import parse_product_page

FIXTURE = ROOT / 'tests' / 'fixtures' / 'product_laptop.html'


def main() -> None:
    settings = Settings(database_url='sqlite:///' + str(ROOT / 'data' / 'sample.db'))
    categories = load_categories(ROOT / 'config' / 'categories.yaml', settings.site_base_url)
    locations = load_locations(ROOT / 'config' / 'locations.yaml')
    db = Database(settings.database_url)
    try:
        db.initialize()
        db.seed_configs(categories, locations)
        raw = FIXTURE.read_text(encoding='utf-8')
        content = parse_product_page(raw, 'https://www.dienmayxanh.com/laptop/acer-aspire-a315', 'laptop')
        product_id = db.upsert_product(ProductLink(url=content.canonical_url, category_code='laptop', source_product_key=content.source_product_key, source='fixture'))
        db.record_content(product_id, content, response_hash='fixture-product-laptop')
        location = locations[0]
        loc_id = db.location_id(location.code)
        price = content.source_location
        snapshot = LocationSnapshot(
            sale_price=price.get('sale_price'), list_price=price.get('list_price'),
            promotion=price.get('promotion') or {}, stock_status=content.stock_status,
            stock_raw=content.stock_raw,
            delivery=DeliveryInfo(status='in_stock', address=location.address + ', ' + location.province_name, method='Giao tận nơi', eta='Trước 18:00 hôm nay'),
            returned_location={'province_id': location.province_id, 'ward_id': location.ward_id, 'province_name': location.province_name, 'ward_name': location.ward_name},
        )
        db.record_location(product_id, loc_id, snapshot, response_hash='fixture-location-hcm')
        rows = db.export_current(100)
        # Keep checked-in fixture exports deterministic; the real DB still
        # contains UUID/timestamps generated by the persistence layer.
        for row in rows:
            row['id'] = 'sample-product-acer-a315'
            row['observed_at'] = '2026-07-17T00:00:00+00:00'
        (ROOT / 'data').mkdir(exist_ok=True)
        (ROOT / 'data' / 'sample.json').write_text(json.dumps(rows, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
        fields = sorted({key for row in rows for key in row})
        with (ROOT / 'data' / 'sample.csv').open('w', encoding='utf-8', newline='') as handle:
            writer = csv.DictWriter(handle, fieldnames=fields, lineterminator='\n')
            writer.writeheader()
            for row in rows:
                writer.writerow({key: json.dumps(value, ensure_ascii=False) if isinstance(value, (dict, list)) else value for key, value in row.items()})
        print(json.dumps({'product_id': product_id, 'rows': len(rows), 'files': ['data/sample.json', 'data/sample.csv']}, ensure_ascii=False))
    finally:
        db.close()


if __name__ == '__main__':
    main()
