import type { HomePageData } from "@/types/home";

export const homePageData: HomePageData = {
  appName: "Điện máy XANH",
  heroSlides: [
    {
      id: "hero-1",
      href: "https://www.dienmayxanh.com/online-only",
      src: "https://cdnv2.tgdd.vn/mwg-static/dmx/Banner/44/d6/44d6c97cbce6b55576448e702f0ebf1c.jpg",
      alt: "Banner Big Campaign Trang chủ",
      title: "Online only",
      description: "Ưu đãi riêng cho khách mua online với deal giá tốt trong ngày.",
    },
    {
      id: "hero-2",
      href: "https://www.dienmayxanh.com/chuong-trinh-cuoi-tuan",
      src: "https://cdnv2.tgdd.vn/mwg-static/dmx/Banner/16/4f/164f304461a312ed99a970a79d2d4548.jpg",
      alt: "bannerbig 2",
      title: "Chương trình cuối tuần",
      description: "Tổng hợp khuyến mãi cuối tuần cho nhóm điện lạnh và gia dụng.",
    },
  ],
  utilityBanners: [
    { id: "paylater", label: "MWG Paylater hạn mức đến 40 triệu" },
    { id: "vpbank", label: "Thẻ tín dụng VPBank MWG hạn mức đến 100 triệu" },
  ],
  categories: [
    {
      id: "cat-1",
      href: "https://www.dienmayxanh.com/may-lanh",
      badge: "5.190k",
      name: "Máy lạnh",
      src: "https://cdnv2.tgdd.vn/mwg-static/common/Common/48/a6/48a6bd2b6d7ad2712eb93772b3578deb.png",
      description: "Điều hòa 1 chiều và inverter giá tốt cho mùa nóng.",
    },
    {
      id: "cat-2",
      href: "https://www.dienmayxanh.com/tu-lanh",
      badge: "HOT",
      name: "Tủ lạnh",
      src: "https://cdnv2.tgdd.vn/mwg-static/dmx/Common/d5/0f/d50fdf576d13d79eb856a5b45614d780.png",
      description: "Tủ lạnh 2 cánh, side-by-side và inverter bán chạy.",
    },
    {
      id: "cat-3",
      href: "https://www.dienmayxanh.com/quat-dieu-hoa",
      name: "Quạt điều hòa",
      src: "https://cdnv2.tgdd.vn/mwg-static/dmx/Common/5e/03/5e03c6e1ce8e5c4bdbde4fcfd96d5322.png",
      description: "Làm mát diện tích lớn, phù hợp phòng khách và phòng ngủ.",
    },
    {
      id: "cat-4",
      href: "https://www.dienmayxanh.com/may-giat",
      badge: "2.990k",
      name: "Máy giặt",
      src: "https://cdnv2.tgdd.vn/mwg-static/dmx/Common/43/66/4366a4dd580185e5a01d56d5e7795afd.png",
      description: "Máy giặt cửa trên, cửa trước và máy giặt sấy.",
    },
    {
      id: "cat-5",
      href: "https://www.dienmayxanh.com/tivi",
      badge: "4.190k",
      name: "Tivi",
      src: "https://cdnv2.tgdd.vn/mwg-static/common/Common/64/d1/64d11a09c75ea322dbc547739886e1d5.png",
      description: "Smart TV 4K, QLED và Google TV nhiều kích cỡ.",
    },
    {
      id: "cat-6",
      href: "https://www.dienmayxanh.com/gia-dung",
      badge: "-50%",
      name: "Gia dụng",
      src: "https://cdnv2.tgdd.vn/mwg-static/dmx/Common/8c/1b/8c1b71a6a8fc062456825e6483b26e6b.png",
      description: "Nồi cơm, nồi chiên, máy xay và thiết bị bếp nhỏ.",
    },
    {
      id: "cat-7",
      href: "https://www.dienmayxanh.com/may-loc-nuoc",
      name: "Máy lọc nước",
      src: "https://cdnv2.tgdd.vn/mwg-static/common/Common/ff/40/ff40b05375a001ea1f246cfd81fcbd12.png",
      description: "Máy lọc nước RO, nóng lạnh và ion kiềm.",
    },
    {
      id: "cat-8",
      href: "https://www.dienmayxanh.com/may-say-quan-ao",
      badge: "4.990k",
      name: "Máy sấy quần áo",
      src: "https://cdnv2.tgdd.vn/mwg-static/dmx/Common/04/b2/04b273113b65fd429271b7fc616c8914.png",
      description: "Máy sấy thông hơi, ngưng tụ và heatpump.",
    },
    {
      id: "cat-9",
      href: "https://www.dienmayxanh.com/tu-dong",
      badge: "3.590k",
      name: "Tủ đông mát",
      src: "https://cdnv2.tgdd.vn/mwg-static/dmx/Common/5f/fc/5ffc124606fecac8c77bceb28b9c5c05.png",
      description: "Bảo quản thực phẩm số lượng lớn cho gia đình và cửa hàng.",
    },
    {
      id: "cat-10",
      href: "https://www.dienmayxanh.com/robot-hut-bui",
      name: "Robot hút bụi",
      src: "https://cdnv2.tgdd.vn/mwg-static/dmx/Common/38/b4/38b4baaf758a3de863095cff982c3ff3.png",
      description: "Robot hút bụi lau nhà với lập lịch dọn dẹp thông minh.",
    },
    {
      id: "cat-11",
      href: "https://www.dienmayxanh.com/quat",
      name: "Quạt",
      src: "https://cdnv2.tgdd.vn/mwg-static/dmx/Common/bc/d4/bcd447fedb2efb22c4060f133cc5498e.png",
      description: "Quạt lửng, quạt đứng, quạt bàn và quạt hộp.",
    },
    {
      id: "cat-12",
      href: "https://www.dienmayxanh.com/noi-com-dien",
      name: "Nồi cơm điện",
      src: "https://cdnv2.tgdd.vn/mwg-static/dmx/Common/4b/2c/4b2c027f7de5232b1fa61e8e6e739d5d.png",
      description: "Nồi cơm điện cơ, tử và cao tần cho gia đình.",
    },
  ],
  flashTabs: [
    {
      id: "flashsale",
      label: "Flashsale",
      src: "https://cdnv2.tgdd.vn/mwg-static/common/Campaign/e8/42/e8423a0c15c70df4fae51120e63a5b22.png",
    },
    {
      id: "tv",
      label: "Tivi WORLDCUP",
      src: "https://cdnv2.tgdd.vn/mwg-static/common/Campaign/99/97/999773e6019817455d43f96fada46db4.png",
    },
    {
      id: "cooling",
      label: "Máy lạnh",
    },
    {
      id: "laundry",
      label: "Máy giặt",
    },
  ],
  flashProducts: [
    {
      id: "flash-1",
      name: "Casper Inverter 1 HP QC-09IU36A",
      sub: "Điều hòa 1 chiều",
      price: 6290000,
      originalPrice: 8990000,
      discount: "-30%",
      remain: "Còn 18/20 suất",
      extra: "Flash sale",
      src: "https://cdn.tgdd.vn/2026/07/timerseo/334018-600x600-1.jpg",
      href: "https://www.dienmayxanh.com/may-lanh/casper-inverter-1-hp-qc-09iu36a?utm_flashsale=1",
      category: "cooling",
      rating: 4.9,
      description: "Mẫu điều hòa bán chạy cho phòng nhỏ, có inverter tiết kiệm điện.",
      highlights: ["Công suất 1 HP", "Inverter", "Lọc bụi mịn cơ bản"],
      ctaLabel: "Thêm vào giỏ",
    },
    {
      id: "flash-2",
      name: "Aqua Inverter 236 lít AQR-T265FA(WFB)",
      sub: "Tủ lạnh ngăn đá trên",
      price: 6190000,
      originalPrice: 7890000,
      discount: "-21%",
      remain: "Còn 5/10 suất",
      extra: "Flash sale",
      src: "https://cdn.tgdd.vn/Products/Images/1943/336960/TimerThumb/336960-600x600-1.jpg",
      href: "https://www.dienmayxanh.com/tu-lanh/tu-lanh-aqua-inverter-236-lit-aqr-t265fa-wfb?utm_flashsale=1",
      category: "flashsale",
      rating: 4.8,
      description: "Dung tích vừa phải cho gia đình 2-3 người, làm lạnh ổn định.",
      highlights: ["236 lít", "Inverter", "Ngăn đá trên"],
      ctaLabel: "Giữ ưu đãi",
    },
    {
      id: "flash-3",
      name: "Samsung Smart TV QLED QA55Q7FA",
      sub: "TV QLED 55 inch",
      price: 9990000,
      originalPrice: 15800000,
      discount: "-36%",
      remain: "Còn 9/15 suất",
      extra: "Flash sale",
      src: "https://cdn.tgdd.vn/2026/07/timerseo/337124-600x600-2.png",
      href: "https://www.dienmayxanh.com/tivi/smart-tivi-qled-samsung-ai-4k-55-inch-qa55q7fa?utm_flashsale=1",
      category: "tv",
      rating: 4.9,
      description: "TV QLED 55 inch nổi bật về màu sắc và giao diện thông minh.",
      highlights: ["QLED 4K", "55 inch", "Smart Hub"],
      ctaLabel: "Xem cấu hình",
    },
    {
      id: "flash-4",
      name: "Máy lọc nước RO Sunhouse UltraPURE SHA8800KL",
      sub: "11 lõi lọc",
      price: 4790000,
      originalPrice: 6890000,
      discount: "-30%",
      remain: "Còn 10/10 suất",
      extra: "Flash sale",
      src: "https://cdn.tgdd.vn/2026/07/timerseo/326045-600x600-1.jpg",
      href: "https://www.dienmayxanh.com/may-loc-nuoc/may-loc-nuoc-ro-sunhouse-sha8800kl-11-loi?utm_flashsale=1",
      category: "flashsale",
      rating: 4.7,
      description: "Thiết bị lọc nước RO nhiều lõi, phù hợp gia đình dùng nước máy.",
      highlights: ["11 lõi", "RO", "Thiết kế tủ đứng"],
      ctaLabel: "Xem chi tiết",
    },
    {
      id: "flash-5",
      name: "Sharp 10 Kg ES-TN101EN-DG",
      sub: "Máy giặt cửa trên",
      price: 4590000,
      originalPrice: 5990000,
      discount: "-23%",
      remain: "Còn 10/10 suất",
      extra: "Flash sale",
      src: "https://cdn.tgdd.vn/2026/07/timerseo/368237-600x600-1.jpg",
      href: "https://www.dienmayxanh.com/may-giat/may-giat-sharp-10-kg-es-tn101en-dg?utm_flashsale=1",
      category: "laundry",
      rating: 4.8,
      description: "Máy giặt cửa trên 10 kg phù hợp gia đình đông người.",
      highlights: ["10 kg", "Cửa trên", "Nhiều chương trình giặt"],
      ctaLabel: "Mua ngay",
    },
  ],
  featuredTabs: [
    { id: "all", label: "Nổi bật" },
    { id: "electronics", label: "Điện tử" },
    { id: "cooling", label: "Máy lạnh" },
    { id: "refrigerator", label: "Tủ lạnh" },
    { id: "laundry", label: "Máy giặt" },
  ],
  featuredProducts: [
    {
      id: "featured-1",
      name: "Casper Inverter 1 HP JC-09IU36X",
      sub: "1 chiều chỉ làm lạnh",
      price: 5990000,
      originalPrice: 7990000,
      discount: "-25%",
      extra: "Mẫu mới - Trả chậm 0% trả trước 0đ",
      rating: 4.9,
      soldLabel: "Đã bán 18,7k",
      src: "https://cdn.tgdd.vn/2026/05/timerseo/363971.jpg",
      href: "https://www.dienmayxanh.com/may-lanh/casper-inverter-1-hp-jc-09iu36x",
      category: "cooling",
      description: "Máy lạnh inverter thế hệ mới cho phòng nhỏ, làm lạnh nhanh và tiết kiệm điện.",
      highlights: ["1 HP", "Inverter", "Mẫu 2026"],
      ctaLabel: "Xem so sánh",
    },
    {
      id: "featured-2",
      name: "Midea Inverter 1 HP MAFA-09CDN8",
      sub: "1 chiều chỉ làm lạnh",
      price: 5190000,
      originalPrice: 8590000,
      discount: "-39%",
      extra: "Trả chậm 0% trả trước 0đ",
      rating: 4.9,
      soldLabel: "Đã bán 64,1k",
      src: "https://cdn.tgdd.vn/2026/07/timerseo/320893.png",
      href: "https://www.dienmayxanh.com/may-lanh/midea-inverter-1-hp-mafa-09cdn8",
      category: "cooling",
      description: "Mẫu điều hòa giá dễ tiếp cận, hợp căn hộ nhỏ và phòng ngủ.",
      highlights: ["1 HP", "Inverter", "Điều khiển dễ dùng"],
      ctaLabel: "Xem gói lắp đặt",
    },
    {
      id: "featured-3",
      name: "Aqua Inverter 358 lít AQR-T410FA(WGB)",
      sub: "Mặt gương mờ",
      price: 9740000,
      originalPrice: 10190000,
      extra: "TRẢ TRƯỚC 0Đ",
      rating: 4.9,
      soldLabel: "Đã bán 16,2k",
      src: "https://cdn.tgdd.vn/2026/07/timerseo/326891.jpg",
      href: "https://www.dienmayxanh.com/tu-lanh/tu-lanh-aqua-inverter-358-lit-aqr-t410fa-wgb",
      category: "refrigerator",
      description: "Tủ lạnh mặt gương mờ với sức chứa rộng và tiết kiệm điện.",
      highlights: ["358 lít", "Mặt gương mờ", "Inverter"],
      ctaLabel: "Xem quà tặng",
    },
    {
      id: "featured-4",
      name: "Quạt điều hoà Daikiosan DKA-03500C 110W",
      sub: "Online giá rẻ quá",
      price: 2590000,
      originalPrice: 4590000,
      discount: "-43%",
      extra: "Trả chậm 0% trả trước 0đ",
      rating: 4.8,
      soldLabel: "Đã bán 11,3k",
      src: "https://cdn.tgdd.vn/Products/Images/7498/218304/TimerThumb/218304-800x800-11.png",
      href: "https://www.dienmayxanh.com/quat-dieu-hoa/may-lam-mat-khong-khi-daikiosan-dka-03500c",
      category: "electronics",
      description: "Quạt điều hòa công suất khá, dùng tốt cho phòng khách mở.",
      highlights: ["110W", "Bình nước lớn", "Làm mát diện rộng"],
      ctaLabel: "Xem thông số",
    },
    {
      id: "featured-5",
      name: "Nagakawa Inverter 1.5 HP NIS-C12R2T62",
      sub: "1 chiều chỉ làm lạnh",
      price: 6190000,
      originalPrice: 9990000,
      discount: "-38%",
      extra: "Mẫu mới",
      rating: 4.9,
      soldLabel: "Đã bán 5,7k",
      src: "https://cdn.tgdd.vn/2026/07/timerseo/361677.png",
      href: "https://www.dienmayxanh.com/may-lanh/nagakawa-inverter-15-hp-nis-c12r2t62",
      category: "cooling",
      description: "Mẫu inverter 1.5 HP cho phòng vừa, hỗ trợ làm lạnh nhanh và vận hành ổn định.",
      highlights: ["1.5 HP", "Mẫu 2026", "Inverter"],
      ctaLabel: "Đặt trước",
    },
  ],
  weeklyBanners: [
    {
      id: "banner-1",
      title: "Tuần lễ thương hiệu",
      src: "https://cdnv2.tgdd.vn/mwg-static/dmx/Banner/30/8f/308fba8a5cbdd28e677b38545e9391ba.png",
      href: "https://www.dienmayxanh.com/chuong-trinh-worldcup-bo-nho-lay-tivi-to",
      description: "Bộ sưu tập deal thương hiệu nổi bật trong tuần.",
    },
    {
      id: "banner-2",
      title: "Gian hàng ưu đãi",
      src: "https://cdnv2.tgdd.vn/mwg-static/dmx/Banner/6d/76/6d763cf2b58f7ef7cddf899d96c71be8.png",
      href: "https://www.dienmayxanh.com/tu-lanh",
      description: "Tổng hợp gian hàng có giá tốt và quà tặng theo ngành hàng.",
    },
    {
      id: "banner-3",
      title: "THÁNG HÃNG LG",
      src: "https://cdnv2.tgdd.vn/mwg-static/dmx/Banner/ad/a6/ada6a6d97c5ce68ca16d00c70e92ffff.png",
      href: "https://www.dienmayxanh.com/khuyen-mai-lg-month",
      description: "Ưu đãi chuyên đề dành riêng cho thiết bị LG.",
    },
  ],
  articles: [
    {
      id: "article-1",
      name: "Mua tủ lạnh Toshiba JAPANDI Kumo tặng ngay nồi cơm điện trị giá 3,25 triệu đồng",
      sub: "Khuyến mãi",
      price: 0,
      src: "https://cdnv2.tgdd.vn/mwg-static/dmx/News/minh%20hoa%20%2814%29639198828664845761.jpg",
      href: "https://www.dienmayxanh.com/khuyen-mai/mua-tu-lanh-toshiba-japandi-kumo-tang-ngay-noi-1595611",
      category: "news",
      publishedAt: "2026-07-17T10:15:00+07:00",
      description: "Ưu đãi dành cho khách hàng mua tủ lạnh Toshiba JAPANDI Kumo trong thời gian chương trình.",
      ctaLabel: "Xem quà tặng",
    },
    {
      id: "article-2",
      name: "ĐẠI HỘI ANDROID – Săn mã giảm đến 800.000đ (15/07-31/07)",
      sub: "Khuyến mãi",
      price: 0,
      src: "https://cdnv2.tgdd.vn/mwg-static/dmx/News/minh%20hoa%20%2815%29639198836213115717.jpg",
      href: "https://www.dienmayxanh.com/khuyen-mai/dai-hoi-android-san-ma-giam-den-800k-1595613",
      category: "news",
      publishedAt: "2026-07-17T09:30:00+07:00",
      description: "Chương trình săn mã giảm giá cho các sản phẩm Android diễn ra từ 15/07 đến 31/07.",
      ctaLabel: "Xem mã ưu đãi",
    },
    {
      id: "article-3",
      name: "LỄ HỘI WORLDCUP TẠI ĐIỆN MÁY XANH: Online giảm to, săn deal giá sốc",
      sub: "Khuyến mãi",
      price: 0,
      src: "https://cdnv2.tgdd.vn/mwg-static/dmx/News/anh%20minh%20hoaa%20%281%29639197227260945550.jpg",
      href: "https://www.dienmayxanh.com/khuyen-mai/worldcup-tai-dien-may-xanh-online-giam-to-1595534",
      category: "news",
      publishedAt: "2026-07-16T10:30:00+07:00",
      description: "Bài viết tổng hợp các deal lớn gắn với chiến dịch World Cup.",
      ctaLabel: "Đọc bản tóm tắt",
    },
  ],
  searchTags: [
    { id: "tag-1", label: "bồn nước" },
    { id: "tag-2", label: "ghế massage" },
    { id: "tag-3", label: "iPhone 15" },
    { id: "tag-4", label: "xe đạp thống nhất" },
    { id: "tag-5", label: "máy massage" },
    { id: "tag-6", label: "máy khoan pin" },
    { id: "tag-7", label: "lọc tổng đầu nguồn" },
    { id: "tag-8", label: "máy lọc nước Korihome" },
    { id: "tag-9", label: "Kangen K8" },
    { id: "tag-10", label: "máy hút bụi Xiaomi" },
    { id: "tag-11", label: "máy rửa bát hafele" },
    { id: "tag-12", label: "MacBook Air M4" },
  ],
  supportContacts: [
    { label: "Gọi mua", value: "1900 232 461", note: "8:00 - 21:30" },
    { label: "Khiếu nại", value: "1800.1063", note: "8:00 - 21:30" },
    { label: "Bảo hành", value: "1900 232 465", note: "8:00 - 21:00" },
  ],
};

export async function fetchHomePageData() {
  await new Promise((resolve) => setTimeout(resolve, 600));

  if (!homePageData.categories.length) {
    throw new Error("Không thể tải danh mục sản phẩm lúc này.");
  }

  return structuredClone(homePageData);
}
